name: cami
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.7.3
  - snakemake-minimal
  - cami-opal=1.0.8.post0
  - openjdk=8
  - sourmash=3.3.1
  - pandas=1
  - taxonomy=0.4
